version: '3.7'
services: 
    bot:
        container_name: scheme-mini-bot
        restart: always
        build: ./app
        volumes:
            - ./data/db:/usr/src/app/src/db/data
            - ./data/google_credentials:/usr/src/app/src/google/credentials
            - ./data/log/debug.log:/usr/src/app/debug.log
        environment: 
            NODE_ENV: production